---

- name: Create melanite service systemd file
  template:
    src: melanite.service.j2
    dest: /etc/systemd/system/melanite.service
    owner: root
    group: root
    mode: 0755

- name: Enable melanite service under systemd
  command: systemctl enable melanite

- name: Start melanite service under systemd
  command: systemctl start melanite
